FROM python:3.9-slim

WORKDIR /tests

RUN pip3 install pipfile-requirements

# Copy over test files.
COPY test/python /test/python/

RUN pipfile2req /test/python/Pipfile.lock > /test/python/requirements.txt
RUN pip3 install -r /test/python/requirements.txt

ENTRYPOINT ["python", "-m", "pytest"]